laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('institucional/{pagina?}', [
    'as'   => 'institucional',
    'uses' => 'InstitucionalController@index'
]);

Route::get('diferenciais', [
    'as'   => 'diferenciais',
    'uses' => 'DiferenciaisController@index'
]);

Route::get('servicos/{pagina?}', [
    'as'   => 'servicos',
    'uses' => 'ServicosController@index'
]);

Route::get('contato', [
    'as'   => 'contato',
    'uses' => 'ContatoController@index'
]);
Route::post('contato', [
    'as'   => 'contato.send',
    'uses' => 'ContatoController@send'
]);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('frase', 'Painel\FraseController');
    Route::resource('banners', 'Painel\BannersController');
    Route::resource('chamadas', 'Painel\ChamadasController');
    Route::resource('cabecalhos', 'Painel\CabecalhosController');
    Route::resource('institucional', 'Painel\InstitucionalController');
    Route::resource('diferenciais', 'Painel\DiferenciaisController');
    Route::resource('servicos', 'Painel\ServicosController');
    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');
    Route::post('ajax/order', 'Painel\AjaxController@order');
});

laravel/app/controllers/painel/AjaxController.php
<?php

namespace Painel;

use \Request, \Input, \DB, \Controller;

class AjaxController extends Controller {

    function order()
    {

        if (!Request::ajax()) return false;

        $menu   = Input::get('data');
        $tabela = Input::get('tabela');

        for ($i = 0; $i < count($menu); $i++) {
            DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
        }

        return json_encode($menu);

    }

}

laravel/app/controllers/painel/BannersController.php
<?php

namespace Painel;

use \Banner, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class BannersController extends BasePainelController {

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return $this->view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return $this->view('painel.banners.create');
    }

    public function store()
    {
        $input = Input::all();
        $rules = Banner::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', Banner::$imagem_config);
            Banner::create($input);
            Session::flash('sucesso', 'Banner criado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar banner.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $banner = Banner::findOrFail($id);

        return $this->view('painel.banners.edit', compact('banner'));
    }

    public function update($id)
    {
        $banner = Banner::findOrFail($id);
        $input  = Input::all();
        $rules  = Banner::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', Banner::$imagem_config);
            } else {
                unset($input['imagem']);
            }

            $banner->update($input);
            Session::flash('sucesso', 'Banner alterado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar banner.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Banner::destroy($id);
            Session::flash('sucesso', 'Banner removido com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover banner.']);

        }
    }

}

laravel/app/controllers/painel/BasePainelController.php
<?php

namespace Painel;

use \View;

class BasePainelController extends \Controller {

    protected $layout = 'painel.common.template';

    protected function setupLayout()
    {
        if ( ! is_null($this->layout))
        {
            $recebidos_count = \ContatoRecebido::naoLidos()->count();
            View::share(compact('recebidos_count'));

            $this->layout = View::make($this->layout);
        }
    }

    protected function view($path, array $data = [])
    {
        $this->layout->content = View::make($path, $data);
    }

}

laravel/app/controllers/painel/CabecalhosController.php
<?php

namespace Painel;

use \Cabecalho, \Input, \Validator, \Session, \Redirect, \CropImage;

class CabecalhosController extends BasePainelController {

    public function index()
    {
        $cabecalhos = Cabecalho::first();

        return $this->view('painel.cabecalhos.index', compact('cabecalhos'));
    }

    public function update($id)
    {
        $cabecalho = Cabecalho::findOrFail($id);
        $input     = Input::all();
        $rules     = Cabecalho::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            foreach ($input as $key => $value) {
                if (Input::hasFile($key)) {
                    $input[$key] = CropImage::make($key, Cabecalho::$imagem_config);
                } else {
                    unset($input[$key]);
                }
            }

            $cabecalho->update($input);
            Session::flash('sucesso', 'Imagens alteradas com sucesso.');

            return Redirect::route('painel.cabecalhos.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar imagens.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/ChamadasController.php
<?php

namespace Painel;

use \Chamada, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class ChamadasController extends BasePainelController {

    public function index()
    {
        $chamadas = Chamada::ordenados()->get();

        return $this->view('painel.chamadas.index', compact('chamadas'));
    }

    public function edit($id)
    {
        $chamada = Chamada::findOrFail($id);

        return $this->view('painel.chamadas.edit', compact('chamada'));
    }

    public function update($id)
    {
        $chamada = Chamada::findOrFail($id);
        $input   = Input::all();
        $rules   = Chamada::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', Chamada::$imagem_config);
            } else {
                unset($input['imagem']);
            }

            $chamada->update($input);
            Session::flash('sucesso', 'Chamada alterada com sucesso.');

            return Redirect::route('painel.chamadas.index');

        } catch (\Exception $e) {

            dd($e);

            return Redirect::back()
                ->withErrors(['Erro ao alterar chamada.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use \Contato, \Input, \Session, \Redirect, \Validator;

class ContatoController extends BasePainelController {

    public function index()
    {
    	$contato = Contato::first();

        return $this->view('painel.contato.index', compact('contato'));
    }

    public function update($id)
    {
        $contato = Contato::findOrFail($id);
        $input   = Input::all();
        $rules   = Contato::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $contato->update($input);
            Session::flash('sucesso', 'Informações de contato alteradas com sucesso.');

            return Redirect::route('painel.contato.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações de contato.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/ContatosRecebidosController.php
<?php

namespace Painel;

use \ContatoRecebido, \Session, \Redirect, \View;

class ContatosRecebidosController extends BasePainelController {

    public function index()
    {
        $contatos_recebidos = ContatoRecebido::orderBy('created_at', 'desc')->get();

        return $this->view('painel.contatosrecebidos.index', compact('contatos_recebidos'));
    }

    public function show($id)
    {
        $contato = ContatoRecebido::findOrFail($id);
        $contato->update(['lido' => 'true']);

        $recebidos_count = ContatoRecebido::naoLidos()->count();
        View::share(compact('recebidos_count'));

        return $this->view('painel.contatosrecebidos.show', compact('contato'));
    }

    public function destroy($id)
    {
        try {

            ContatoRecebido::destroy($id);
            Session::flash('sucesso', 'Mensagem removida com sucesso.');

            return Redirect::route('painel.contato.recebidos.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover mensagem.']);

        }
    }

}

laravel/app/controllers/painel/DiferenciaisController.php
<?php

namespace Painel;

use \Diferenciais, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class DiferenciaisController extends BasePainelController {

    public function index()
    {
        $diferenciais = Diferenciais::first();

        return $this->view('painel.diferenciais.edit', compact('diferenciais'));
    }

    public function update($id)
    {
        $diferenciais = Diferenciais::findOrFail($id);
        $input        = Input::all();
        $rules        = Diferenciais::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', Diferenciais::$imagem_config);
            } else {
                unset($input['imagem']);
            }

            $diferenciais->update($input);
            Session::flash('sucesso', 'Página alterada com sucesso.');

            return Redirect::route('painel.diferenciais.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar página.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/FraseController.php
<?php

namespace Painel;

use \Frase, \Input, \Session, \Redirect, \Validator;

class FraseController extends BasePainelController {

    public function index()
    {
        $frase = Frase::first();

        return $this->view('painel.frase.edit', compact('frase'));
    }

    public function update($id)
    {
        $frase = Frase::findOrFail($id);
        $input = Input::all();

        $validate = Validator::make($input, Frase::$rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $frase->update($input);
            Session::flash('sucesso', 'Frase alterada com sucesso.');

            return Redirect::route('painel.frase.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar frase.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/HomeController.php
<?php

namespace Painel;

use \View, \Input, \Auth, \Session, \Redirect;

class HomeController extends BasePainelController {

    public function index()
    {
        return $this->view('painel.home');
    }

    public function login()
    {
        return $this->view('painel.login');
    }

    public function attempt()
    {
        $authvars = array(
            'username' => Input::get('username'),
            'password' => Input::get('password')
        );

        $lembrar = (Input::get('lembrar') == 'true') ? true : false;

        if (Auth::attempt($authvars, $lembrar)) {
            return Redirect::route('painel.home');
        } else {
            Session::flash('login_errors', true);
            return Redirect::route('painel.login')->withInput(Input::except('password'));
        }
    }

    public function logout()
    {
        Auth::logout();
        return Redirect::route('home');
    }

}

laravel/app/controllers/painel/InstitucionalController.php
<?php

namespace Painel;

use \Institucional, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class InstitucionalController extends BasePainelController {

    public function index()
    {
        $institucional = Institucional::all();

        return $this->view('painel.institucional.index', compact('institucional'));
    }

    public function edit($id)
    {
        $institucional = Institucional::findOrFail($id);

        return $this->view('painel.institucional.edit', compact('institucional'));
    }

    public function update($id)
    {
        $institucional = Institucional::findOrFail($id);
        $input         = Input::all();
        $rules         = Institucional::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', Institucional::$imagem_config);
            } else {
                unset($input['imagem']);
            }

            $institucional->update($input);
            Session::flash('sucesso', 'Página alterada com sucesso.');

            return Redirect::route('painel.institucional.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar página.'])
                ->withInput();

        }
    }

}

laravel/app/views/painel/common/nav.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url() }}">{{ Config::get('projeto.name') }}</a>
        </div>

    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li class="dropdown @if(preg_match('~painel.(frase|banners|chamadas)~', Route::currentRouteName())) active @endif">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ route('painel.frase.index') }}">Frase</a></li>
                    <li><a href="{{ route('painel.banners.index') }}">Banners</a></li>
                    <li><a href="{{ route('painel.chamadas.index') }}">Chamadas</a></li>
                </ul>
            </li>

            <li @if(str_is('painel.cabecalhos*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.cabecalhos.index') }}">Cabeçalhos</a>
            </li>

            <li @if(str_is('painel.institucional*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.institucional.index') }}">Institucional</a>
            </li>

            <li @if(str_is('painel.diferenciais*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.diferenciais.index') }}">Diferenciais</a>
            </li>

            <li @if(str_is('painel.servicos*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.servicos.index') }}">Serviços</a>
            </li>

            <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contato @if($recebidos_count>=1)<span class="badge">{{ $recebidos_count }}</span>@endif <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
                    <li><a href="{{ route('painel.contato.recebidos.index') }}">Contatos Recebidos @if($recebidos_count>=1)<span class="badge">{{ $recebidos_count }}</span>@endif</a></li>
                </ul>
            </li>

            <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                    <li><a href="{{ route('painel.logout') }}">Logout</a></li>
                </ul>
            </li>
        </ul>
    </div>
    </div>
</nav>

laravel/app/views/painel/common/template.blade.php
<?php $login = (Route::currentRouteName() == 'painel.login'); ?>
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ Config::get('projeto.name') }} - Painel Administrativo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('../assets/css/painel/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('../assets/css/painel/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('../assets/css/painel/painel.min.css') }}">

    <script>var BASE = '{{ asset('index.php/') }}';</script>
</head>
<body class="{{ ($login ? 'login' : 'painel') }}">
    @if(!$login)
        @include('painel.common.nav')
    @endif

    <div class="{{ ($login ? 'wrapper' : 'main container') }}">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset('../assets/js/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('../assets/js/painel/vendor.min.js') }}"></script>
    <script src="{{ asset('../assets/js/painel/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('../assets/js/painel/painel.js') }}"></script>
</body>
</html>